name: alarm_app
description: "An advanced alarm system app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-128.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  time_picker_spinner: ^1.0.2
  alarm: ^5.0.3
  cron: ^0.6.1
  path_provider: ^2.1.5
  zeroconnect: ^1.5.1
  uuid: ^4.5.1
  shared_preferences: ^2.5.2
  qr_code_scanner_plus: ^2.0.10+1
  carousel_slider: ^5.0.0
  device_info_plus: ^11.3.3
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
